baseURL = "https://mustafasakalli.me/"
languageCode = "tr"
title = "Yazılar"
theme = "m10c"

SectionPagesMenu = "main"

enableEmoji = true
[menu]
    [[menu.main]]
        identifier = "about"
        Name = "about"
        url = "/about/"
        weight = 1
[taxonomies]
    tag = "tags"
    author = "Mustafa Sakallı"
    preserveTaxonomyNames = true


[permalinks]
    post = "/blog/:title/"


[params]

    site_logo = "code.svg"
  description = "Personal Website of Mustafa Sakallı "
    [[params.social]]
    name = "github"
    url = "https://github.com/mustafasakalli"
    [[params.social]]
    name = "twitter"
    url = "https://twitter.com/mstfsakalli" 

    [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/mustafasakalli"  

    