baseURL = "https://mustafasakalli.me/"
languageCode = "tr"
title = "Mustafa Sakallı"
theme = "m10c"

SectionPagesMenu = "main"

enableEmoji = true
[menu]
    [[menu.main]]
        identifier = "about"
        Name = "About"
        url = "/about/"
        weight = 0
[taxonomies]
    tag = "tags"
    author = "Mustafa Sakallı"
    preserveTaxonomyNames = true


[permalinks]
    post = "/blog/:title/"


[params]

    author = "Mustafa Sakallı Lord"
    description = "Trying to be a software developer."
    avatar = "/background.jpg"

    [[params.social]]
    name = "github"
    url = "https://github.com/mustafasakalli"
    
    [[params.social]]
    name = "twitter"
    url = "https://twitter.com/mstfsakalli" 

    [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/mustafasakalli"  

    