baseURL = "http://example.org/"
languageCode = "en-us"
title = "Personal Website of Mustafa Sakallı"
theme = "ananke"

SectionPagesMenu = "main"

enableEmoji = true
[menu]
    [[menu.main]]
        identifier = "about"
        Name = "About"
        url = "/about/"
        weight = 0
[taxonomies]
    tag = "tags"
    author = "Mustafa Sakallı"
    preserveTaxonomyNames = true


[permalinks]
    post = "/blog/:title/"


[params]
    favicon = ""
    description = "The last theme you'll ever need. Maybe."
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = "https://github.com/mustafasakalli"
    gitlab = ""
    linkedin = "https://linkedin.com/in/mustafasakalli"
    mastodon = ""
    slack = ""
    stackoverflow = ""
    rss = ""
    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-red"
    featured_image = "facebook_cover.png"
    recent_posts_number = 3
    show_reading_time = true
    site_logo = ""